management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/company_details
    username: root
    password: akshay
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
