spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  hibernate:
    ddl-auto: create-drop
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
